social/Post/urls.py
from django.urls import path
from .views import list_posts, like_post, post_detail_view, Analitic_Posts_View

app_name = 'Post'

urlpatterns = [
    path('', list_posts, name='list_posts'),
    path('liked/',like_post , name='like_post'),
    path('<int:id>/', post_detail_view, name='post-detail'),
    path('analitics/date_from=<date_from>&date_to=<date_to>/', Analitic_Posts_View.as_view(), name='post_likes'),
]   

social/social/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home_view, name='home_page'),
    
    path('User/', include('User.urls', namespace='User')),
    path('Post/', include('Post.urls', namespace='Post')),
]

social/Post/models.py
from django.db import models
from User.models import UserModel
from django.core.validators import FileExtensionValidator
from django.urls import reverse

# Create your models here.

class PostModel(models.Model):
    title = models.TextField()
    image = models.ImageField(upload_to='Post/static/images', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    liked = models.ManyToManyField(UserModel, blank=True, related_name='likes')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='Posts') # 

    def __str__(self):
        return str(self.title[:20])

    def num_likes(self):
        return self.liked.all().count()

    def num_comments(self):
        return self.comentpostmodel_set.all().count()


    def get_absolute_url(self):
        return reverse("Post:post-detail", kwargs={"id": self.id})

    
    class Meta:
        ordering = ('-created',)


class ComentPostModel(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    post = models.ForeignKey(PostModel, on_delete=models.CASCADE)
    comment = models.TextField(max_length=500)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)


LIKE_CHOICES = (
    ('like', 'like'),
    ('unlike', 'unlike'),
)


class LikeModel(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    post = models.ForeignKey(PostModel, on_delete=models.CASCADE)
    like = models.CharField(choices=LIKE_CHOICES, max_length=9)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} - {self.post} - {self.like}"

social/Post/forms.py
from django import forms
from .models import PostModel, ComentPostModel

class PostModelForm(forms.ModelForm):
    title = forms.CharField(widget=forms.Textarea(attrs={'rows':2}))
    class Meta:
        model = PostModel
        fields = ['title', 'image']

class CommentPostModelForm(forms.ModelForm):
    comment = forms.CharField(label='',
        widget=forms.TextInput(attrs={'placeholder': 'Comment the post here'}))
    class Meta:
        model = ComentPostModel
        fields = ['comment']

social/Post/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from .models import PostModel, LikeModel
from User.models import UserModel
from .forms import PostModelForm, CommentPostModelForm

import json
from User.serializers import LikeSerializer
from rest_framework import generics

# Create your views here.


def list_posts(request):
    if request.user.is_authenticated == False:
        return redirect("home_page")
    all_posts = PostModel.objects.all()
    user = UserModel.objects.get(username=request.user.username)
    post_form = PostModelForm()
    comment_form = CommentPostModelForm()

    if 'name_for_post_form' in request.POST:
        print(request.POST)
        post_form = PostModelForm(request.POST, request.FILES)
        if post_form.is_valid():
            obj_form = post_form.save(commit=False) # form is not saved yet
            obj_form.author = user
            obj_form.save()
            post_form = PostModelForm()
    
    if 'name_for_comment_form' in request.POST:
        print(request.POST)
        comment_form = CommentPostModelForm(request.POST)
        if comment_form.is_valid():
            obj_form = comment_form.save(commit=False) # form is not saved yet
            obj_form.user = user
            obj_form.post = PostModel.objects.get(id=request.POST.get('id2'))
            obj_form.save()
            comment_form = CommentPostModelForm()
    
    context = {
        'all_posts':all_posts,
        'account':user,
        'post_form':post_form,
        'comment_form':comment_form,
    }
    print(user)
    return render(request, "Post/list_posts.html", context)


def like_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('id')
        post = PostModel.objects.get(id=post_id)
        account = UserModel.objects.get(username=user.username) #username=request.user.username
        if account in post.liked.all():
            post.liked.remove(account)
        else:
            post.liked.add(account)

        like,created = LikeModel.objects.get_or_create(user=account, post_id=post_id) 
        #created is boolen value, if created =True it means that the post didn't exist before, it was created
        if not created:
            if like.like=='Like':
                like.like='Unlike'
            else:
                like.like = 'Like'
        else:
            like.like = 'Like'

            post.save()
            like.save()
        # like."like" is value of LikeModel

    return redirect("Post:list_posts")


def post_detail_view(request, id):
    obj = get_object_or_404(PostModel, id=id)
    context = {
        "postname": obj.title,
        "post":obj,
    }
    return render(request, "Post/post_info.html", context)


# Example url: /api/analitics/?date_from=2020-02-02&date_to=2020-02-15
class Analitic_Posts_View(generics.ListAPIView):
    serializer_class = LikeSerializer
#Example url: http://127.0.0.1:8000/Post/analitics/date_from%3D2021-09-19&date_to%3D2021-09-2/

    def get(self, request, *args, **kwargs):
        likes_analitic = LikeModel.objects.filter(created__range=[kwargs['date_from'], kwargs['date_to']])
        if len(likes_analitic) > 0:
            mimetype = 'application/json'
            return HttpResponse(f'likes by period: {len(likes_analitic)}')
        else:
            return HttpResponse("no likes on this period")

social/Post/templates/Post/list_posts.html
{% extends 'base_post.html' %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
<form action="" method="POST" enctype="multipart/from-data">
    <h2>Create post here</h2>
    {% csrf_token %}{{post_form.as_p}}<button type="submit" name="name_for_post_form">Publish</button>
</form>

<h1>All posts</h1>
<ul>
    {% for post in all_posts %}
    <p>
        <form action="{% url 'Post:like_post' %}" method="POST" id="post.id"> {% csrf_token %}
            <input type="hidden" name="id" value={{post.id}}>
            <li><!--{{post.author.user}}<br>--><a href="{{ post.get_absolute_url }}">{{ post }}</a>   <button type="submit">
                {% if account not in post.liked.all %}Like{% else %}Unlike{% endif %}</button> <i>author:</i> {{ post.author.username }}; <i>created:</i> {{ post.created|timesince}} ago
            </li>
        <i>likes:</i>{{post.liked.count}}<br><i>comments</i> {{post.num_comments}}:<ul>
            {% for i in post.comentpostmodel_set.all %}
                <li>{{ i.user.username }}<br>{{i.comment }};</li>
            {% endfor %}</ul><br>
        {% if post.coment_set.all %}{% for comment in post.coment_set.all %}{{comment.comment}}{% endfor %}{% endif %}
        </form>
        <form action="" method="POST">
            {% csrf_token %}
            <input type="hidden" name="id2" value={{post.id}}>
            {{comment_form}}
            <button type="submit" name="name_for_comment_form">Comment</button>
        </form>
    </p>
    {% endfor %}    
</ul>

{% endblock %}

social/Post/templates/Post/post_info.html
{% extends 'base.html' %}

{% block title %}
post info
{% endblock title %}

{% block content %}
<h2>Post: {{postname}} </h2>
<h2>Post analytics:</h2><br>
<button><a href="../">Back</a></button>
{% endblock %}