social/Post/urls.py
from django.urls import path
from .views import list_posts, like_post, post_detail_view, Analitic_Posts_View

app_name = 'Post'

urlpatterns = [
    path('', list_posts, name='list_posts'),
    path('liked/',like_post , name='like_post'),
    path('<int:id>/', post_detail_view, name='post-detail'),
    path('analitics/date_from=<date_from>&date_to=<date_to>/', Analitic_Posts_View.as_view(), name='post_likes'),
]   

social/User/urls.py
from django.urls import path
from .views import account_view, account_detail_view, RegisterView, LoginView, UserView, Logout, LastUserLoginView

app_name = 'User'

urlpatterns = [
    path('sign_up', RegisterView.as_view(), name='sign_up_page'),
    path('sign_in', LoginView.as_view(), name='sign_in_page'),
    path('log_out', Logout.as_view(), name='log_out_page'),

    path('account', account_view, name='account_page'),
    path('<int:id>/', account_detail_view, name='account-detail'),
    path('lastuser_login/<int:pk>', LastUserLoginView.as_view(), name='user_activity'),
]

social/social/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home_view, name='home_page'),
    
    path('User/', include('User.urls', namespace='User')),
    path('Post/', include('Post.urls', namespace='Post')),
]

social/templates/main/home_page.html
{% extends 'base.html' %}

{% block content %}
<h1>This is the main page</h1>
<h2>Posts</h2>
<ul>
    {% for post in all_posts %}
        <li><i>Author:</i> {{post.author.user}}. <i>Post title:</i> {{ post }}...</li>
    {% endfor %}
</ul>
<h2>Users</h2>
<ul>
    {% for user in all_users %}
        <for><li>{{user.id}} - <a href="{{ user.get_absolute_url }}">{{ user.username }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

social/templates/main/nav_bar.html
<nav>
    <ul>
        <li><a href={%url "home_page"%}>Main page</a></li>
        <li><a href={%url "User:account_page"%}>Account</a></li>
        <li><a href={%url "Post:list_posts"%}>Posts</a></li>
    </ul>
    <ul>
        <li><a href="#">Sign up</a></li>
        <li><a href="#">Sign in</a></li>
        <li><a href="#">Log out</a></li>
    </ul>
</nav>